/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function BlackBox({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/black-box.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[20.53, 54.97, -97.53]} rotation={[1.99, 0.08, -2.96]}>
        <PerspectiveCamera
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={22.9}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[-1.12, 4.28, 0.74]}
        scale={3.43}
      />
    </group>
  );
}

useGLTF.preload("/black-box.glb");
